### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by dayangac** [HisarCS/F360#1]
- [x] ### Task List
- [ ]  Complete the shapes avalible in Fusion 360 sketches(apart from the spline)
- [ ]  Complete the features set which currently at 3 features
- [x] Write documentation for current shapes
- [ ] Write documentation for all classes
- [ ] Add images for all classes
- [x] Add images for current classes
